env_name: "prod"
app_dir: "/opt/examc"
compose_project_name: "examc"
compose_profiles: ""

debug: false
secure_ssl_redirect: true
session_cookie_secure: true
csrf_cookie_secure: true
use_ssl: true

allowed_hosts: ["examc.epfl.ch","localhost","127.0.0.1"]
csrf_trusted_origins: ["https://examc.epfl.ch"]

tz: "Europe/Zurich"
private_media_root: "/private_media"

db_host: "10.95.33.52"
db_port: 3306

celery_broker_url: "redis://redis:6379/0"
celery_result_backend: "redis://redis:6379/0"
celery_task_always_eager: false
