$ANSIBLE_VAULT;1.1;AES256
30383939373035656363623132626265303961313230386333643739376365306662346331323863
6137346136366432376230353837663464633133303533630a363533303535376237356561323835
31303630383631613365373637393639326139633961643865663564343339333134363634346561
6134383139663335350a393730363935333437383531653065646631386364396533393565633832
31323665623361626165323932356161383334393262323136363030323465356561656539326436
34643636323137643332633739306338636533643164666336333263326366323233343930376264
65323161653834613834323939346635393465633435623263663431303233353531663738313436
62646263386436333562393330383434373563663863306239326263336165623835616434303232
39653166363731363433386566343236633232336464313762646464663135643165383266383236
61363361333464643534656434623338626234643438613361363239386238343731363561666561
34623935636164333565363364666639633439643034353735343933383630613737646662333264
38643666656164643261346434353632636263303262363364306164656237626363386462663464
66353463363863333830313231323135333538613931343538656139303661323864343062353833
38376563346638343563363336333866636637623331353532353162333433653066633866383134
30313061363730666163646130373563353364363734346337643536396439636161313462626435
64633035626464343561316434333064653964343963303030376236373662353663653138643933
65643361616432653633356437613437623335396561303334633337626337396238363135613864
33656136343465626564333964613964373533663434613561303138663233666437653036626434
31363331326339326463323366346563323930336436313833363563303531633937353936326632
38343337313732623935313439613638376630393134616239646263326633376165343533323465
36313666316132333938613637316165313366663962363461646233383838313436316231326234
37343030316561376432383464376264333036396564373738616433303538333232376433303332
30323164303261353839656339356261376336303131633566643961333461313664623466613938
63646434343535616231
