env_name: "dev"
debug: true
secure_ssl_redirect: false
session_cookie_secure: false
csrf_cookie_secure: false
use_ssl: false
compose_profiles: "mysql-dockerized"
compose_project_name: "examc"

allowed_hosts:
  - "localhost"
  - "127.0.0.1"
  - "0.0.0.0"

csrf_trusted_origins:
  - "http://localhost"
  - "http://127.0.0.1"
  - "http://0.0.0.0"
  - "http://localhost:8000"
  - "http://127.0.0.1:8000"

tz: "Europe/Zurich"
private_media_root: "/private_media"

db_host: "mysql"
db_port: 3306

celery_broker_url: "redis://redis:6379/0"
celery_result_backend: "redis://redis:6379/0"
celery_task_always_eager: true

constance_redis_connection: "redis://127.0.0.1:6379/0"
